version: '3.5'
services:
 zabbix-server:
  build: 
   context: ./server-mysql/alpine
   cache_from:
    - alpine:3.12
  image: zabbix/zabbix-server-mysql:alpine-5.0-latest
  container_name: zabbix-server
  hostname: zabbix-server
  restart: always
  ports:
   - "10051:10051"
  volumes:
   -  /etc/localtime:/etc/localtime:ro
   -  /etc/timezone:/etc/timezone:ro 
   - ./config/etc/zabbix:/etc/zabbix:rw
   - ./config/zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - ./config/zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ./config/zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./config/zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./config/zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ./config/zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
   - ./config/zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
  links:
   - zabbix-java-gateway:zabbix-java-gateway
  user: root
  env_file:
   - .env_db_mysql
  depends_on:
   - zabbix-java-gateway
   - zabbix-snmptraps
  networks:
   zbx_net_backend:
     aliases:
      - zabbix-server
      - zabbix-server-mysql
      - zabbix-server-alpine-mysql
      - zabbix-server-mysql-alpine
   zbx_net_frontend:
  stop_grace_period: 30s

 zabbix-web-apache-mysql:
  build:
   context: ./web-apache-mysql/alpine
   cache_from:
    - alpine:3.12
  image: zabbix-web-apache-mysql:alpine-local
  container_name: apache2
  hostname: apache2
  restart: always
  ports:
   - "80:80"
   - "443:443"
  links:
   - zabbix-server:zabbix-server
  env_file:
   - .env_web
  user: root
  depends_on:
   - zabbix-server
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-web-apache-mysql
     - zabbix-web-apache-alpine-mysql
     - zabbix-web-apache-mysql-alpine
   zbx_net_frontend:   
  stop_grace_period: 10s
  sysctls:
   - net.core.somaxconn=65535
  labels:
   com.zabbix.description: "Zabbix frontend on Apache web-server with MySQL database support"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "apache2"
   com.zabbix.os: "alpine"
 
 zabbix-java-gateway:
  build:
   context: ./java-gateway/alpine
   cache_from:
    - alpine:3.12
  image: zabbix-java-gateway:alpine-local
  container_name: zabbix-java-gateway
  hostname: zabbix-java-gateway
  restart: always
  ports:
   - "10052:10052"
  env_file:
   - .env_java
  user: root
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-java-gateway
     - zabbix-java-gateway-alpine
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix Java Gateway"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "java-gateway"
   com.zabbix.os: "alpine"

 zabbix-snmptraps:
  build:
   context: ./snmptraps/alpine
   cache_from:
    - alpine:3.12
  image: zabbix-snmptraps:alpine-local
  container_name: zabbix-snmptraps
  hostname: zabbix-snmptraps
  restart: always
  ports:
   - "162:162/udp"
  volumes:
   - ./config/zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
  user: root
  networks:
   zbx_net_frontend:
    aliases:
     - zabbix-snmptraps
   zbx_net_backend:
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix snmptraps"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "snmptraps"
   com.zabbix.os: "ubuntu"

 zabbix-agent:
  build:
   context: ./agent/alpine
   cache_from:
     - alpine:3.12
  image: zabbix-agent:alpine-local
  ports:
   - "10050:10050"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
   - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
  links:
     - zabbix-server:zabbix-server
  depends_on:
    - zabbix-server
  labels:
     com.zabbix.description: "Zabbix agent"
     com.zabbix.company: "Zabbix SIA"
     com.zabbix.component: "zabbix-agentd"
     com.zabbix.os: "alpine"
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-agent
     - zabbix-agent-passive
     - zabbix-agent-alpine
  stop_grace_period: 5s


networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
